# Generated by Django 3.2 on 2021-04-10 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator', models.CharField(max_length=100)),
                ('accountability', models.IntegerField(default=0)),
                ('commitment', models.PositiveIntegerField(default=0)),
                ('conflict', models.PositiveIntegerField(default=0)),
                ('trust', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, related_name='evaluator_evaluatee', to='evaluat.Evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('githubRepo', models.CharField(max_length=100)),
                ('evaluations', models.ManyToManyField(blank=True, related_name='group_evaluations', to='evaluat.Evaluation')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='evaluat.user')),
                ('students', models.ManyToManyField(related_name='user_groups', to='evaluat.User')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluatee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='evaluatee', to='evaluat.user'),
        ),
    ]
