# Generated by Django 3.2 on 2021-04-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluat', '0004_group_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='group_user', to='evaluat.Group'),
        ),
    ]
